### PR TITLE
linux-tegra: Update GPIO to enable SPI

### PR DESCRIPTION
**Pull request by volks73**
Adds a custom DTB that enables the SPI pins in the 40-pin header of the Jetson AGX Orin Dev Kit. The 40-pin header defaults to GPIO. This DTB was generated using the jetson-io utility that is supplied with L4T and JetPack to configure the 40-pin header. The DTB has been verified by uploading to balenaOS devices and using the device configuration feature in balenaCloud.

I was not sure where to include the DTB in the folder structure and if the jetson-dtbs.bb is correct. I was following [this example](https://github.com/balena-os/balena-jetson/commit/3dbf9c96e5986c2138f318d1ee9f0d5c1a2fc3c8) from the [Custom Device Trees](https://docs.balena.io/learn/develop/hardware/i2c-and-spi/#custom-device-trees) documentation.

### CODE REVIEW

**Comment by acostach** [comment]
@resin-jenkins test this please

**Review by acostach — COMMENTED** [review]
lgtm

**Comment by acostach** [comment]
Superseded by https://github.com/balena-os/balena-jetson-orin/pull/426

**Comment by volks73** [comment]
Should I close this PR?

**Comment by acostach** [comment]
Hi @volks73 , yes, you can close it. The other PR where I pushed your changes seem to fail to build but I didn't get the chance to look at why linux-tegra fails at the install step. Did the build work for you locally?

**Comment by volks73** [comment]
I will close and we can continue conversation in #426.

**Comment by acostach** [comment]
No problem @volks73 , I will look into the build failure in the next few days and fix it

**Pull request closed without merging**
