### PR TITLE
[WIP] Orin Nano

### PR DESCRIPTION
**Pull request by acostach**
This is a WIP PR for Orin Nano support in balenaOS

### CODE REVIEW

**Comment by dremsol** [comment]
@acostach I'm trying to trigger a build from this branch such that I can test the fan speed. However, I bump into some issues starting the build.

first updating the submodules resutls in
```bash
git submodule update
Submodule path 'layers/meta-tegra': checked out '23b28202eb413792e5c00e6a5cb128e3c47ada6c'
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'layers/poky', but it did not contain debd42be214be6bce50a0f0a2fe186b20e6fe6bc. Direct fetching of that commit failed.
fatal:
```

build command
```bash
./balena-yocto-scripts/build/barys \                                                                                                                                                                   
    --remove-build \
    --development-image \
    --log \
    --shared-downloads /var/cache/yocto/downloads \
    --shared-sstate /var/cache/yocto/sstate-cache \
    -m jetson-orin-nano-devkit-nvme
```
results in

```bash
ERROR: ParseError at /home/willem/projects/hawkeye/balena-jetson-orin/build/../layers/meta-tegra/conf/layer.conf:58: unparsed line: 'addpylib ${LAYERDIR}/lib oe4t'
```

**Comment by acostach** [comment]
@dremsol it's because our poky mirror has been updated recently and the addpylib backport branch was erased. I pushed the branch once more and you should be able to pull it now.

As for the fan speed, looks like with the precompiled uefi_jetson.bin and Ubuntu, the fan speed is normal. With the uefi_jetson.bin compiled by us from meta-tegra sources, the speed is increased. A workaround is to not install nvfancontrol in the rootfs at all, or, modify the nvfancontrol file and seta lower speed for temp 0.

I pushed a WIP branch in jetson-flash that you can use to provision the Orin Nano with the local built flasher image, it's named orin_nano_flash_support. I still need to update the docs for it and test it with the Orin NX, that's why I haven't opened a PR just yet.

**Comment by dremsol** [comment]
The following error seems to have something to do with our server. 

```
| #3 [internal] load metadata for docker.io/library/debian:bullseye
| #3 ERROR: failed to authorize: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fdebian%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io on 127.0.0.53:53: dial udp 127.0.0.53:53: connect: network is unreachable
| ------
|  > [internal] load metadata for docker.io/library/debian:bullseye:
| ------
| Dockerfile:1
| --------------------
|    1 | >>> FROM debian:bullseye
|    2 |
|    3 |     VOLUME /mnt/sysroot/inactive
| --------------------
| ERROR: failed to solve: failed to fetch anonymous token: Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fdebian%3Apull&service=registry.docker.io": dial tcp: lookup auth.docker.io on 127.0.0.53:53: dial udp 127.0.0.53:53: connect: network is unreachable
| Error response from daemon: invalid reference format
| WARNING: exit code 1 from a shell command.
```

However, once pulling the image manually and running the build again i stumble upon the following
```
❯ cat  /home/willem/projects/hawkeye/balena-jetson-orin/build/tmp/work/x86_64-linux/mkfs-hostapp-native/1.0-r0/temp/log.do_compile
DEBUG: Executing shell function do_compile
#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 220B done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/debian:bullseye
#3 DONE 0.0s

#4 [1/3] FROM docker.io/library/debian:bullseye
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 334B done
#5 DONE 0.0s

#6 [2/3] RUN apt-get update && apt-get install -y       ca-certificates         iptables
#6 CACHED

#7 [3/3] COPY create.* /usr/bin/
#7 CACHED

#8 exporting to image
#8 exporting layers done
#8 writing image sha256:7782e1d30738c5a9b51dff654d0ad3ddc677c0f2810226312999f3174256f8c0 0.0s done
#8 DONE 0.0s
Error response from daemon: invalid reference format
WARNING: exit code 1 from a shell command.
```

**Comment by acostach** [comment]
I'm not seeing this error when using ubuntu 18.04 (see balena-yocto-scripts dockerfile) as a build host, I suspect it may happen with a different or newer build setup. It's worth trying to purge all docker images, see if the issue persists.

**Comment by acostach** [comment]
Container GPU access smoke test passed at this revision:
```
CUDA Clock sample
GPU Device 0: "Ampere" with compute capability 8.7

Average clocks/block = 1965.765625
```

**Comment by acostach** [comment]
Merging for staging testing

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Comment by dremsol** [comment]
@acostach thanks for pointing me to the Dockerfile, I was not aware of their existence. Running the build after purgin the `debian` image using

```bash
./balena-yocto-scripts/build/balena-build.sh -d jetson-orin-nano-devkit-nvme -s /var/cache/yocto/ -k  
```

results in
```bash
cat ./build/tmp/work/x86_64-linux/mkfs-hostapp-native/1.0-r0/temp/log.do_compile.3506
DEBUG: Executing shell function do_compile
cgroups: cgroup mountpoint does not exist: unknown
Error response from daemon: No such image: bd67afc56e52
WARNING: exit code 1 from a shell command.
```

**Comment by acostach** [comment]
Are you using ubuntu 18.04 for the build or something else?

**Comment by dremsol** [comment]
The script is using `Ubuntu-18-04` as a base image in following [Dockerfile](https://github.com/balena-os/balena-yocto-scripts/blob/master/automation/Dockerfile_yocto-build-env)

**Pull request merged**
