### PR TITLE
AGX Orin support on Kirkstone

### PR DESCRIPTION
**Pull request by acostach**

### CODE REVIEW

**Comment by acostach** [comment]
This is a work in progress PR, still need to:
 - check and update partition offsets and sizes
 - create signed boot image for the SPI Flash based on the boot binaries generated by tegraflash
 - further test the altboot & health rollbacks
 - further test the custom dtb support

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins ok to test

**Comment by mikhail-vl** [comment]
@acostach Thank you for your hard work supporting Orin. Appreciate it!

**Comment by acostach** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by acostach** [comment]
@balena-ci I self-certify!

**Pull request merged**
